export const enum PageRouter {
    Home = "/",
    Current = "/users/current",
    Login = "/login",
    Contact = "/contact",
    // intentions = "/intentions",
    Announcement = "/announcements",
    AnnouncementPreview = "/announcements/preview",
    AnnouncementEdit = "/announcements/edit",

    Intentions = "/intentions",
    IntentionsEdit = "/intentions/edit",
    IntentionsPreview = "/intentions/preview",

    UserCurrent = "/users/current",
    Users = "/users",
    Article = "/articles",
    ArticlePreview = "/articles/preview",
    ArticleEdit = "/article/edit",
    ArticleCreate = "/article/create",

    Gallery = "/gallery",
    Parish = "/parish",
    ParishCouncil = "/parish/council",
    ParishOffice = "/parish/office",
    ParishPriests = "/parish/priests-history",
    Ministry = "/ministry",
    MinistrySacrament = "/ministry/sacrament",
    MinistryGroups = "/ministry/groups",
}
